services:
  n8n:
    image: n8nio/n8n:latest
    user: "1000:1000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
    ports:
      - "5678:5678"

    labels:
      - traefik.enable=true
      - traefik.http.routers.n8n.rule=Host(`${SUBDOMAIN}.${DOMAIN_NAME}`)
      - "traefik.http.services.n8n.loadbalancer.server.port=5678"
      - traefik.http.routers.n8n.tls=true
      - traefik.http.routers.n8n.entrypoints=web,websecure
      - traefik.http.routers.n8n.tls.certresolver=mytlschallenge
      - traefik.http.middlewares.n8n.headers.SSLRedirect=true
      - traefik.http.middlewares.n8n.headers.STSSeconds=315360000
      - traefik.http.middlewares.n8n.headers.browserXSSFilter=true
      - traefik.http.middlewares.n8n.headers.contentTypeNosniff=true
      - traefik.http.middlewares.n8n.headers.forceSTSHeader=true
      - traefik.http.middlewares.n8n.headers.SSLHost=${DOMAIN_NAME}
      - traefik.http.middlewares.n8n.headers.STSIncludeSubdomains=true
      - traefik.http.middlewares.n8n.headers.STSPreload=true
      - traefik.http.routers.n8n.middlewares=n8n@docker
    environment:
     # - N8N_RESTRICT_FILE_ACCESS_TO=/home/node/.n8n-files,/home/node/.n8n
      - NODES_EXCLUDE=[]
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=false
      - N8N_STORAGE_PATH=/home/node/.n8n-files/temp
      - N8N_HOST=${SUBDOMAIN}.${DOMAIN_NAME}
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - NODE_ENV=production
      - N8N_PROXY_HOPS=1
      - WEBHOOK_URL=https://${SUBDOMAIN}.${DOMAIN_NAME}/
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n_db
      - DB_POSTGRESDB_USER=n8n_user
      - DB_POSTGRESDB_PASSWORD=${DB_PASSWORD}
    volumes:
      - n8n_data:/home/node/.n8n
      - /home/sasha/n8n-local-files:/home/node/.n8n-files:rw
    networks:
      - n8n_default

volumes:
  n8n_data:
    external: true

networks:
  n8n_default:
    external: true
